# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku - CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: |
          npm run build
          npm run test
          
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 4f1d2830-357c-492a-8b30-1354ae1f9f05
          heroku_app_name: 'polar-shelf-45776'
          heroku_email: 'kirillsakharov@yahoo.co.uk'
          buildpack: 'heroku/nodejs'
          branch: 'main'
